// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let dbUrl = process.env["DATABASE_URL"] || "file:./dev.db";
if (!dbUrl.startsWith("file:") && !dbUrl.startsWith("postgres") && !dbUrl.startsWith("mysql")) {
  dbUrl = `file:${dbUrl}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
